### ISSUE TITLE
global-tunnel doesn't work with Hyperledger Fabric

### ISSUE THREAD

**Issue by nospam2000** [np-maintain/global-tunnel#14]
globalTunnel._makeRequest checks if _options.host_ is set, but Hyperledger Fabric is using _options.hostname_ instead which causes the proxy to be bypassed.

The documentation of [http.request(options[, callback])](https://nodejs.org/api/http.html#http_http_request_options_callback) says the following about host and hostname in options:

```
options
    host <string> A domain name or IP address of the server to issue the request to. Default: 'localhost'.
    hostname <string> Alias for host. To support url.parse(), hostname is preferred over host.

```
That means both is legal to use.
I already made a fix together with @bigbelette, see pull request #15.

**Comment by MarcoScabbiolo** [comment]
Hi @nospam2000 your PR has been merged and published to npm, is the issue solved for you?

**Comment by nospam2000** [comment]
Yes, this specific issue is solved. Thanks for integrating it sooo fast!
