### ISSUE TITLE
How to exclude proxy for few domains ?

### ISSUE THREAD

**Issue by ourdex86** [np-maintain/global-tunnel#25]
I am creating a webhook for one of my project using NodeJS. I am making external API calls from this webhook. I want all the requests to go through the proxy except few API requests.

To make all the requests go through the proxy I am using this [global-tunnel-ng](https://www.npmjs.com/package/global-tunnel-ng)

But I don't see an option to exclude this proxy for few domains. Can someone help me in achieving this ?

**Comment by MarcoScabbiolo** [comment]
There is no such option for the moment, PR #13 adds that option but is not ready to be merged yet.
