### ISSUE TITLE
Do not manipulate env variables

### ISSUE THREAD

**Issue by gajus** [np-maintain/global-tunnel#40]
```js
export HTTP_PROXY=http://proxy-gateway
node -e "const globalTunnel = require('global-tunnel-ng'); console.log('a', process.env.HTTP_PROXY); globalTunnel.initialize(); console.log('b', process.env.HTTP_PROXY);"
a http://proxy-gateway
b undefined

```

`b` should be equal to `a`.

**Comment by MarcoScabbiolo** [comment]
See https://github.com/np-maintain/global-tunnel/blob/51413dcf0534252b5049ec213105c7063ccc6367/index.js#L116 . This would be a breaking change. This is intentionally done to prevent double proxy handling by other modules that also check the environment variables.

**The actual environment variable is not manipulated, only Node's environment variables are**

**Comment by gajus** [comment]
> The actual environment variable is not manipulated, only Node's environment variables are

Your module should not try to look after what other modules are doing. Thats their responsibility.

This behaviour prevents solution-agnostic detection of the HTTP proxy presence.

**Comment by MarcoScabbiolo** [comment]
This module is being maintained as it is was conceived by the initial developers, we will not make breaking changes.

**Comment by MarcoScabbiolo** [comment]
Hey @gajus , I've told the `yeoman` community about your package, here is the gitter channel: Join the chat: https://gitter.im/yeoman/yeoman . I implemented `global-tunnel` there a while ago and they are considering migrating to `global-agent`.
