### ISSUE TITLE
Recommend a lightweight alternative

### ISSUE THREAD

**Issue by gajus** [np-maintain/global-tunnel#41]
Thank you for maintaining `global-tunnel` fork. I have been using the past couple of months but kept running into hard to debug issues in the recent Node.js versions. I have started by looking if I can patch `global-tunnel`/ `tunnel`, but it appears that it has been developed with intent to support legacy Node.js versions and that makes it hard to patch/ debug.

I have developed https://github.com/gajus/global-agent, which works with Node.js v12 and above. If you would you like to become a contributor to the latter email me at gajus@gajus.com. 

If you consider this as a viable alternative please suggest `global-agent` in your documentation.

**Comment by MarcoScabbiolo** [comment]
Hey @gajus , thanks for passing by, I'll link to it.
